# local_env.yml: Contains settings and credentials.
# ONLY used in development mode! DO NOT commit any credentials in this file to git!

# S3 credentials/settings
S3_ENDPOINT_URL: ''
S3_ACCESS_KEY: ''
S3_SECRET_KEY: ''
S3_BUCKET_REGION: ''
S3_BUCKET_NAME: ''

# YouTube API key
YT_API_KEY: ''

# Google Cloud TTS API key
GOOGLE_TTS_API_KEY: ''

# Auth0 credentials
AUTH0_CLIENT_ID: ''
AUTH0_CLIENT_SECRET: ''